# Generated by Django 5.1.4 on 2025-09-09 19:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_created_at'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allowed_locations',
            field=models.ManyToManyField(blank=True, help_text='Locations this user is allowed to operate in', related_name='allowed_users', to='location.location'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_change_location',
            field=models.BooleanField(default=False, help_text='Whether user can override their default location'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_location',
            field=models.ForeignKey(blank=True, help_text="Default location for this user's operations", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_users', to='location.location'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('employee', 'Employee')], default='employee', help_text='User role in the system', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number must be in international format', max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
