# Generated by Django 5.1.4 on 2025-08-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0003_purchaseorder_is_paid_purchaseorder_payment_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_terms',
            field=models.PositiveIntegerField(blank=True, help_text='Payment terms in days for this specific order', null=True),
        ),
    ]
