# Generated by Django 5.1.4 on 2025-08-22 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0004_add_payment_terms_to_order'),
        ('suppliers', '0003_remove_supplier_last_invoice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='payment_terms',
            field=models.PositiveIntegerField(blank=True, default=30, help_text='Payment terms in days for this specific order', null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='suppliers.supplier'),
        ),
    ]
