# Generated by Django 5.1.4 on 2025-08-23 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0005_alter_purchaseorder_payment_terms_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purchaseorderitem',
            unique_together=set(),
        ),
    ]
