# Generated by Django 5.1.3 on 2024-11-12 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorymovement',
            old_name='number',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='number',
            new_name='quantity',
        ),
    ]
