# Generated by Django 5.1.4 on 2025-05-08 02:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0002_rename_number_inventorymovement_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorymovement',
            name='type',
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'input'), ('OUT', 'output'), ('ADJ', 'adjusting')], default='IN', max_length=3),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory_management.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
