# Generated by Django 5.1.4 on 2025-05-30 19:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0004_product_is_active_alter_inventorymovement_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'Input'), ('OUT', 'Output'), ('ADJ', 'Adjusting')], default='IN', max_length=3),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
