# Generated by Django 5.1.4 on 2025-08-25 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0006_inventorymovement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Unit price at the time of the movement (mainly for INPUT movements)', max_digits=10, null=True),
        ),
    ]
