# Generated by Django 5.1.4 on 2025-09-09 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0007_inventorymovement_unit_price'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='destination_location',
            field=models.ForeignKey(blank=True, help_text='Destination location for transfers', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='location.location'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movements', to='location.location'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'Input'), ('OUT', 'Output'), ('ADJ', 'Adjusting'), ('TRF', 'Transfer')], default='IN', max_length=3),
        ),
        migrations.CreateModel(
            name='ProductLocationStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_stocks', to='location.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_locations', to='inventory_management.product')),
            ],
            options={
                'ordering': ['location__name', 'product__name'],
                'unique_together': {('product', 'location')},
            },
        ),
    ]
