# Generated by Django 5.1.4 on 2025-08-20 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='last_invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='payment_terms',
            field=models.PositiveIntegerField(default=30, help_text='Payment terms in days (default is 30 days)'),
        ),
    ]
