# Generated by Django 5.1.4 on 2025-08-22 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_supplier_last_invoice_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='last_invoice_date',
        ),
    ]
