# Generated by Django 5.1.4 on 2025-08-23 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_remove_supplier_last_invoice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='payment_terms',
            field=models.PositiveIntegerField(default=30, help_text='Default payment terms in days (default is 30 days)'),
        ),
    ]
